{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{- if .Values.persistence.config.annotations }}
  annotations:
{{ toYaml .Values.persistence.config.annotations | indent 4 }}
{{- end }}
  name: {{ template "sickchill.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "sickchill.fullname" . }}
    helm.sh/chart: {{ include "sickchill.chart" . }}
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}

{{- if .Values.persistence.config.selector }}
  selector:
{{ toYaml .Values.persistence.config.selector | indent 4 }}
{{- end}}

{{- if .Values.persistence.config.storageClass }}
{{- if (eq "-" .Values.persistence.config.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.config.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
